# Generated by Django 5.2.1 on 2025-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_category_menuitem_delete_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="quantity",
            field=models.SmallIntegerField(default=0),
        ),
    ]
