# Generated by Django 5.2.1 on 2025-06-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("restaurant", "0003_category_menuitem_delete_menu"),
    ]

    operations = [
        migrations.RemoveField(model_name="menuitem", name="category",),
        migrations.AlterField(
            model_name="orderitem",
            name="menuitem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurant.menuitem"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="menuitem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurant.menuitem"
            ),
        ),
        migrations.RemoveField(model_name="orderitem", name="unit_price",),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="api.order",
            ),
        ),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="MenuItem",),
    ]
